services:
  keycloak:
    build: 
      dockerfile: Dockerfile
      context: ./keycloak
    ports:
      - "8075:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
